#!/usr/bin/env python3
"""Content definitions for weeks 5-20."""

WEEKS_5_TO_20 = {
    5: {
        "en": {"title": "Activity History: Week 5 - Modules and Packages", "developer_label": "Developer", "page_label": "Page", "generated_msg": "Activity log generated",
            "sections": [
                {"id": 1, "title": "I. Importing Modules", "paragraphs": ["The import statement loads modules for use in a program. Import the entire module with 'import module' or specific items with 'from module import item'. The 'as' keyword creates an alias for the imported name.", "Standard library modules provide pre-built functionality. The math module offers mathematical functions. The datetime module handles dates and times. The os module provides operating system interfaces.", "Module search path includes the current directory, PYTHONPATH, and installation directories. The sys.path list shows the search order. Relative imports use dots to navigate package structure."], "label": "Import Patterns", "items": ["import module loads entire module", "from module import item loads specific items", "as keyword creates aliases", "Standard library provides extensive functionality"]},
                {"id": 2, "title": "II. Creating Modules", "paragraphs": ["Any Python file is a module. The filename without .py extension is the module name. Functions, classes, and variables defined in the file become module attributes. The module is loaded once and cached.", "The if __name__ == '__main__' block runs only when the file is executed directly, not when imported. This pattern allows modules to serve as both importable libraries and standalone scripts.", "Module documentation uses docstrings at the file level. The __doc__ attribute contains the docstring. Module-level constants are defined in uppercase. Private names start with underscore."], "label": "Module Structure", "items": ["Filename becomes module name", "__name__ == '__main__' for script execution", "Docstrings document module purpose", "Underscore prefix indicates private names"]},
                {"id": 3, "title": "III. Packages and __init__.py", "paragraphs": ["A package is a directory containing Python files and an __init__.py file. The __init__.py file marks the directory as a package. It can be empty or contain initialization code.", "Subpackages are nested directories with their own __init__.py files. Import paths use dots as separators: package.subpackage.module. The __all__ list controls what 'from package import *' exports.", "Package structure organizes related modules. Common patterns include separating models, views, and utilities. The __init__.py can import submodule contents for convenient access."], "label": "Package Organization", "items": ["Directory with __init__.py is a package", "Dot notation for nested imports", "__all__ controls star imports", "Organize related modules in packages"]},
                {"id": 4, "title": "IV. Standard Library and Project", "paragraphs": ["The Python standard library includes modules for file handling, data processing, networking, and more. The os.path module manipulates file paths. The json module serializes data. The collections module provides specialized containers.", "Documentation at docs.python.org describes all standard library modules. The help() function provides interactive documentation. Dir() lists module attributes.", "The week project creates a utility package with multiple modules. The package includes file utilities, string helpers, and data validators. The __init__.py exposes the main API."], "label": "Project Implementation", "items": ["Standard library covers common tasks", "os.path for path manipulation", "json for data serialization", "Package exposes clean API through __init__.py"]}
            ]},
        "fr": {"title": "Historique d'activité : Semaine 5 - Modules et Packages", "developer_label": "Développeur", "page_label": "Page", "generated_msg": "Historique d'activité généré",
            "sections": [
                {"id": 1, "title": "I. Importation de modules", "paragraphs": ["L'instruction import charge les modules pour utilisation. Importer le module entier avec 'import module' ou des éléments spécifiques avec 'from module import item'. Le mot-clé 'as' crée un alias.", "Les modules de la bibliothèque standard fournissent des fonctionnalités prêtes. Le module math offre des fonctions mathématiques. datetime gère les dates et heures. os fournit des interfaces système.", "Le chemin de recherche inclut le répertoire courant, PYTHONPATH, et les répertoires d'installation. La liste sys.path montre l'ordre de recherche."], "label": "Modèles d'import", "items": ["import module charge le module entier", "from module import item charge des éléments", "as crée des alias", "Bibliothèque standard extensive"]},
                {"id": 2, "title": "II. Création de modules", "paragraphs": ["Tout fichier Python est un module. Le nom de fichier sans .py est le nom du module. Les fonctions, classes et variables deviennent des attributs du module. Le module est chargé une fois et mis en cache.", "Le bloc if __name__ == '__main__' s'exécute seulement quand le fichier est exécuté directement, pas quand il est importé. Ce modèle permet aux modules de servir comme bibliothèques et scripts.", "La documentation utilise des docstrings au niveau fichier. L'attribut __doc__ contient la docstring. Les constantes sont en majuscules."], "label": "Structure du module", "items": ["Nom de fichier devient nom de module", "__name__ == '__main__' pour exécution script", "Docstrings documentent le module", "Préfixe underscore indique noms privés"]},
                {"id": 3, "title": "III. Packages et __init__.py", "paragraphs": ["Un package est un répertoire contenant des fichiers Python et un __init__.py. Le fichier __init__.py marque le répertoire comme package. Il peut être vide ou contenir du code d'initialisation.", "Les sous-packages sont des répertoires imbriqués avec leurs propres __init__.py. Les chemins d'import utilisent des points comme séparateurs. La liste __all__ contrôle les exports de 'from package import *'.", "La structure de package organise les modules liés. Les modèles courants séparent modèles, vues et utilitaires. Le __init__.py peut importer le contenu des sous-modules."], "label": "Organisation des packages", "items": ["Répertoire avec __init__.py est un package", "Notation pointée pour imports imbriqués", "__all__ contrôle les imports étoile", "Organiser modules liés en packages"]},
                {"id": 4, "title": "IV. Bibliothèque standard et projet", "paragraphs": ["La bibliothèque standard Python inclut des modules pour fichiers, données, réseau, etc. os.path manipule les chemins. json sérialise les données. collections fournit des conteneurs spécialisés.", "La documentation sur docs.python.org décrit tous les modules. La fonction help() fournit de la documentation. Dir() liste les attributs.", "Le projet crée un package utilitaire avec plusieurs modules. Le package inclut des utilitaires fichier, helpers chaîne et validateurs. Le __init__.py expose l'API principale."], "label": "Implémentation du projet", "items": ["Bibliothèque standard couvre tâches courantes", "os.path pour manipulation de chemins", "json pour sérialisation", "Package expose API via __init__.py"]}
            ]},
        "cs": {"title": "Historie aktivit: Týden 5 - Moduly a balíčky", "developer_label": "Vývojář", "page_label": "Strana", "generated_msg": "Historie aktivit vygenerována",
            "sections": [
                {"id": 1, "title": "I. Importování modulů", "paragraphs": ["Příkaz import načítá moduly pro použití v programu. Import celého modulu pomocí 'import module' nebo specifických položek pomocí 'from module import item'. Klíčové slovo 'as' vytváří alias.", "Moduly standardní knihovny poskytují předpřipravené funkce. Modul math nabízí matematické funkce. datetime zpracovává data a časy. os poskytuje rozhraní operačního systému.", "Vyhledávací cesta zahrnuje aktuální adresář, PYTHONPATH a instalační adresáře. Seznam sys.path ukazuje pořadí vyhledávání."], "label": "Vzory importu", "items": ["import module načítá celý modul", "from module import item načítá specifické položky", "as vytváří aliasy", "Standardní knihovna poskytuje rozsáhlé funkce"]},
                {"id": 2, "title": "II. Vytváření modulů", "paragraphs": ["Jakýkoli Python soubor je modul. Název souboru bez .py je název modulu. Funkce, třídy a proměnné definované v souboru se stávají atributy modulu. Modul je načten jednou a uložen do cache.", "Blok if __name__ == '__main__' běží pouze když je soubor spuštěn přímo, ne když je importován. Tento vzor umožňuje modulům sloužit jako importovatelné knihovny i samostatné skripty.", "Dokumentace modulu používá docstrings na úrovni souboru. Atribut __doc__ obsahuje docstring. Konstanty jsou velkými písmeny."], "label": "Struktura modulu", "items": ["Název souboru se stává názvem modulu", "__name__ == '__main__' pro spuštění skriptu", "Docstrings dokumentují účel modulu", "Prefix podtržítko označuje privátní názvy"]},
                {"id": 3, "title": "III. Balíčky a __init__.py", "paragraphs": ["Balíček je adresář obsahující Python soubory a soubor __init__.py. Soubor __init__.py označuje adresář jako balíček. Může být prázdný nebo obsahovat inicializační kód.", "Podbalíčky jsou vnořené adresáře s vlastními __init__.py. Importní cesty používají tečky jako oddělovače. Seznam __all__ řídí co exportuje 'from package import *'.", "Struktura balíčku organizuje související moduly. Běžné vzory oddělují modely, pohledy a utility. __init__.py může importovat obsah submodulů."], "label": "Organizace balíčků", "items": ["Adresář s __init__.py je balíček", "Tečková notace pro vnořené importy", "__all__ řídí hvězdičkové importy", "Organizovat související moduly do balíčků"]},
                {"id": 4, "title": "IV. Standardní knihovna a projekt", "paragraphs": ["Standardní knihovna Pythonu zahrnuje moduly pro práci se soubory, zpracování dat, síťování a další. os.path manipuluje cesty souborů. json serializuje data. collections poskytuje specializované kontejnery.", "Dokumentace na docs.python.org popisuje všechny moduly. Funkce help() poskytuje interaktivní dokumentaci. Dir() vypisuje atributy modulu.", "Týdenní projekt vytváří balíček utility s více moduly. Balíček zahrnuje souborové utility, pomocníky pro řetězce a validátory dat."], "label": "Implementace projektu", "items": ["Standardní knihovna pokrývá běžné úkoly", "os.path pro manipulaci cest", "json pro serializaci dat", "Balíček exponuje API přes __init__.py"]}
            ]}
    },
    6: {
        "en": {"title": "Activity History: Week 6 - Object-Oriented Programming Part 1", "developer_label": "Developer", "page_label": "Page", "generated_msg": "Activity log generated",
            "sections": [
                {"id": 1, "title": "I. Classes and Objects", "paragraphs": ["A class is a blueprint for creating objects. The class keyword defines a class. Class names use PascalCase convention. Objects are instances of classes created by calling the class like a function.", "The __init__ method initializes object attributes when an instance is created. The self parameter refers to the instance being created. Instance attributes are assigned using self.attribute = value.", "Each object has its own copy of instance attributes. Class attributes are shared among all instances. Access attributes using dot notation: object.attribute."], "label": "Class Basics", "items": ["class ClassName: defines a class", "__init__(self) initializes instances", "self refers to the current instance", "Dot notation accesses attributes"]},
                {"id": 2, "title": "II. Methods and Self", "paragraphs": ["Methods are functions defined inside a class. Instance methods take self as the first parameter. The self parameter provides access to instance attributes and other methods.", "Methods can modify instance state. They can also return values like regular functions. Method calls use dot notation: object.method(). Python passes self automatically.", "Methods can call other methods using self. This enables building complex behaviors from simple operations. Keep methods focused on single tasks for maintainability."], "label": "Working with Methods", "items": ["Methods are functions in classes", "self provides instance access", "Call methods: object.method()", "Methods can call other methods via self"]},
                {"id": 3, "title": "III. Encapsulation", "paragraphs": ["Encapsulation bundles data and methods that operate on that data. Objects hide internal implementation details. Public interfaces expose only necessary functionality.", "Python uses naming conventions for access control. Single underscore prefix (_name) suggests internal use. Double underscore prefix (__name) triggers name mangling for stronger privacy.", "Properties provide controlled access to attributes. The @property decorator creates a getter. The @attribute.setter decorator creates a setter. Properties maintain encapsulation while providing attribute-like syntax."], "label": "Data Protection", "items": ["Encapsulation hides implementation details", "_name convention for internal attributes", "__name triggers name mangling", "@property creates getters and setters"]},
                {"id": 4, "title": "IV. Class Design and Project", "paragraphs": ["Good class design follows single responsibility principle. Each class should have one reason to change. Keep classes focused and cohesive. Avoid classes that do too many things.", "Use meaningful names for classes and methods. Document classes with docstrings. Include type hints for clarity. Test classes with unit tests.", "The week project implements a bank account class. The class manages balance, deposits, and withdrawals. Methods enforce business rules like preventing negative balances. Properties provide read-only access to balance."], "label": "Project Implementation", "items": ["BankAccount class manages money", "deposit() and withdraw() methods", "Property prevents negative balance", "Transaction history tracking"]}
            ]},
        "fr": {"title": "Historique d'activité : Semaine 6 - POO Partie 1", "developer_label": "Développeur", "page_label": "Page", "generated_msg": "Historique d'activité généré",
            "sections": [
                {"id": 1, "title": "I. Classes et objets", "paragraphs": ["Une classe est un modèle pour créer des objets. Le mot-clé class définit une classe. Les noms de classe utilisent PascalCase. Les objets sont des instances créées en appelant la classe comme une fonction.", "La méthode __init__ initialise les attributs quand une instance est créée. Le paramètre self réfère à l'instance en cours de création. Les attributs d'instance sont assignés avec self.attribut = valeur.", "Chaque objet a sa propre copie des attributs d'instance. Les attributs de classe sont partagés entre toutes les instances. Accéder aux attributs avec la notation pointée."], "label": "Bases des classes", "items": ["class NomClasse: définit une classe", "__init__(self) initialise les instances", "self réfère à l'instance courante", "Notation pointée accède aux attributs"]},
                {"id": 2, "title": "II. Méthodes et self", "paragraphs": ["Les méthodes sont des fonctions définies dans une classe. Les méthodes d'instance prennent self comme premier paramètre. self donne accès aux attributs et autres méthodes.", "Les méthodes peuvent modifier l'état de l'instance. Elles peuvent aussi retourner des valeurs. Les appels utilisent la notation pointée. Python passe self automatiquement.", "Les méthodes peuvent appeler d'autres méthodes via self. Cela permet de construire des comportements complexes. Garder les méthodes focalisées sur des tâches uniques."], "label": "Travail avec les méthodes", "items": ["Les méthodes sont des fonctions dans les classes", "self donne accès à l'instance", "Appel: objet.methode()", "Méthodes peuvent s'appeler entre elles"]},
                {"id": 3, "title": "III. Encapsulation", "paragraphs": ["L'encapsulation regroupe données et méthodes. Les objets cachent les détails d'implémentation. Les interfaces publiques exposent seulement les fonctionnalités nécessaires.", "Python utilise des conventions de nommage. Le préfixe underscore simple (_nom) suggère usage interne. Le préfixe double (__nom) déclenche le name mangling.", "Les propriétés fournissent un accès contrôlé. Le décorateur @property crée un getter. @attribut.setter crée un setter. Les propriétés maintiennent l'encapsulation."], "label": "Protection des données", "items": ["Encapsulation cache l'implémentation", "_nom pour attributs internes", "__nom déclenche name mangling", "@property crée getters et setters"]},
                {"id": 4, "title": "IV. Conception et projet", "paragraphs": ["Une bonne conception suit le principe de responsabilité unique. Chaque classe devrait avoir une seule raison de changer. Garder les classes focalisées et cohésives.", "Utiliser des noms significatifs. Documenter avec des docstrings. Inclure des type hints. Tester avec des tests unitaires.", "Le projet implémente une classe compte bancaire. La classe gère le solde, dépôts et retraits. Les méthodes appliquent les règles métier. Les propriétés donnent un accès en lecture seule."], "label": "Implémentation du projet", "items": ["Classe CompteBancaire gère l'argent", "Méthodes depot() et retrait()", "Propriété empêche solde négatif", "Suivi historique des transactions"]}
            ]},
        "cs": {"title": "Historie aktivit: Týden 6 - OOP Část 1", "developer_label": "Vývojář", "page_label": "Strana", "generated_msg": "Historie aktivit vygenerována",
            "sections": [
                {"id": 1, "title": "I. Třídy a objekty", "paragraphs": ["Třída je šablona pro vytváření objektů. Klíčové slovo class definuje třídu. Názvy tříd používají PascalCase. Objekty jsou instance tříd vytvořené voláním třídy jako funkce.", "Metoda __init__ inicializuje atributy objektu při vytvoření instance. Parametr self odkazuje na vytvářenou instanci. Atributy instance se přiřazují pomocí self.atribut = hodnota.", "Každý objekt má vlastní kopii atributů instance. Atributy třídy jsou sdíleny mezi všemi instancemi. Přístup k atributům pomocí tečkové notace."], "label": "Základy tříd", "items": ["class NazevTridy: definuje třídu", "__init__(self) inicializuje instance", "self odkazuje na aktuální instanci", "Tečková notace přistupuje k atributům"]},
                {"id": 2, "title": "II. Metody a self", "paragraphs": ["Metody jsou funkce definované uvnitř třídy. Metody instance berou self jako první parametr. Parametr self poskytuje přístup k atributům instance a dalším metodám.", "Metody mohou modifikovat stav instance. Mohou také vracet hodnoty jako běžné funkce. Volání metod používá tečkovou notaci. Python předává self automaticky.", "Metody mohou volat jiné metody pomocí self. To umožňuje budovat komplexní chování z jednoduchých operací."], "label": "Práce s metodami", "items": ["Metody jsou funkce ve třídách", "self poskytuje přístup k instanci", "Volání: objekt.metoda()", "Metody mohou volat jiné metody přes self"]},
                {"id": 3, "title": "III. Zapouzdření", "paragraphs": ["Zapouzdření sdružuje data a metody, které s nimi pracují. Objekty skrývají interní implementační detaily. Veřejná rozhraní exponují pouze nezbytné funkce.", "Python používá konvence pojmenování pro řízení přístupu. Prefix jedno podtržítko (_název) naznačuje interní použití. Prefix dvojité podtržítko (__název) spouští name mangling.", "Properties poskytují kontrolovaný přístup k atributům. Dekorátor @property vytváří getter. @atribut.setter vytváří setter."], "label": "Ochrana dat", "items": ["Zapouzdření skrývá implementační detaily", "_název konvence pro interní atributy", "__název spouští name mangling", "@property vytváří gettery a settery"]},
                {"id": 4, "title": "IV. Návrh tříd a projekt", "paragraphs": ["Dobrý návrh tříd následuje princip jediné odpovědnosti. Každá třída by měla mít jeden důvod ke změně. Udržujte třídy zaměřené a soudržné.", "Používejte smysluplné názvy pro třídy a metody. Dokumentujte třídy docstringy. Zahrňte type hints pro jasnost. Testujte třídy unit testy.", "Týdenní projekt implementuje třídu bankovního účtu. Třída spravuje zůstatek, vklady a výběry. Metody vynucují obchodní pravidla."], "label": "Implementace projektu", "items": ["Třída BankovniUcet spravuje peníze", "Metody vklad() a vyber()", "Property zabraňuje zápornému zůstatku", "Sledování historie transakcí"]}
            ]}
    },
    7: {
        "en": {"title": "Activity History: Week 7 - Object-Oriented Programming Part 2", "developer_label": "Developer", "page_label": "Page", "generated_msg": "Activity log generated",
            "sections": [
                {"id": 1, "title": "I. Inheritance Basics", "paragraphs": ["Inheritance allows classes to derive from other classes. The child class inherits attributes and methods from the parent. Specify the parent class in parentheses: class Child(Parent).", "Child classes can add new attributes and methods. They can also override inherited methods. The super() function accesses the parent class. Use super().__init__() to call parent initialization.", "Inheritance models 'is-a' relationships. A Dog is an Animal. A Car is a Vehicle. Use inheritance when subclasses share behavior with parent classes."], "label": "Inheritance Concepts", "items": ["class Child(Parent): inherits from Parent", "Child inherits parent attributes and methods", "super() accesses parent class", "Models 'is-a' relationships"]},
                {"id": 2, "title": "II. Method Overriding", "paragraphs": ["Child classes can redefine inherited methods. The new method replaces the parent's version for child instances. Method signatures should match for proper overriding.", "Use super() to extend rather than replace parent behavior. Call super().method() then add child-specific code. This preserves parent functionality while adding features.", "The method resolution order (MRO) determines which method is called. Python searches from child to parent classes. The __mro__ attribute shows the order."], "label": "Overriding Methods", "items": ["Define method with same name to override", "super().method() calls parent version", "MRO determines method lookup order", "Extend parent behavior with super()"]},
                {"id": 3, "title": "III. Multiple Inheritance", "paragraphs": ["Python supports inheriting from multiple classes. List parent classes separated by commas: class Child(Parent1, Parent2). Methods are resolved left to right using MRO.", "Multiple inheritance can lead to complexity. The diamond problem occurs when parents share a grandparent. Python's MRO handles this systematically.", "Prefer composition over multiple inheritance. Include objects as attributes rather than inheriting from many classes. This reduces coupling and improves flexibility."], "label": "Multiple Parents", "items": ["class Child(Parent1, Parent2): multiple parents", "MRO resolves method conflicts", "Diamond problem handled by MRO", "Composition often preferred over inheritance"]},
                {"id": 4, "title": "IV. Abstract Classes and Project", "paragraphs": ["Abstract classes define interfaces without implementation. The abc module provides AbstractBaseClass and abstractmethod decorator. Abstract methods must be implemented by subclasses.", "Abstract classes cannot be instantiated directly. They ensure subclasses provide required methods. Use for defining common interfaces across related classes.", "The week project implements a shape hierarchy. An abstract Shape class defines area() and perimeter() methods. Circle, Rectangle, and Triangle classes implement these methods with specific formulas."], "label": "Project Implementation", "items": ["ABC module for abstract classes", "@abstractmethod marks required methods", "Shape hierarchy with Circle, Rectangle, Triangle", "Each subclass implements area() and perimeter()"]}
            ]},
        "fr": {"title": "Historique d'activité : Semaine 7 - POO Partie 2", "developer_label": "Développeur", "page_label": "Page", "generated_msg": "Historique d'activité généré",
            "sections": [
                {"id": 1, "title": "I. Bases de l'héritage", "paragraphs": ["L'héritage permet aux classes de dériver d'autres classes. La classe enfant hérite des attributs et méthodes du parent. Spécifier la classe parent entre parenthèses: class Enfant(Parent).", "Les classes enfant peuvent ajouter des attributs et méthodes. Elles peuvent aussi redéfinir les méthodes héritées. La fonction super() accède à la classe parent. Utiliser super().__init__() pour appeler l'initialisation parent.", "L'héritage modélise les relations 'est-un'. Un Chien est un Animal. Une Voiture est un Véhicule. Utiliser l'héritage quand les sous-classes partagent le comportement."], "label": "Concepts d'héritage", "items": ["class Enfant(Parent): hérite de Parent", "Enfant hérite attributs et méthodes", "super() accède à la classe parent", "Modélise les relations 'est-un'"]},
                {"id": 2, "title": "II. Redéfinition de méthodes", "paragraphs": ["Les classes enfant peuvent redéfinir les méthodes héritées. La nouvelle méthode remplace la version du parent pour les instances enfant. Les signatures doivent correspondre.", "Utiliser super() pour étendre plutôt que remplacer. Appeler super().methode() puis ajouter le code spécifique. Cela préserve les fonctionnalités parent.", "L'ordre de résolution des méthodes (MRO) détermine quelle méthode est appelée. Python recherche de l'enfant vers les parents. L'attribut __mro__ montre l'ordre."], "label": "Redéfinition de méthodes", "items": ["Définir méthode de même nom pour redéfinir", "super().methode() appelle version parent", "MRO détermine l'ordre de recherche", "Étendre le comportement parent avec super()"]},
                {"id": 3, "title": "III. Héritage multiple", "paragraphs": ["Python supporte l'héritage de plusieurs classes. Lister les parents séparés par virgules. Les méthodes sont résolues de gauche à droite avec MRO.", "L'héritage multiple peut mener à la complexité. Le problème du diamant survient quand les parents partagent un grand-parent. Le MRO de Python gère cela systématiquement.", "Préférer la composition à l'héritage multiple. Inclure des objets comme attributs plutôt qu'hériter de plusieurs classes. Cela réduit le couplage."], "label": "Parents multiples", "items": ["class Enfant(Parent1, Parent2): parents multiples", "MRO résout les conflits de méthodes", "Problème du diamant géré par MRO", "Composition souvent préférée"]},
                {"id": 4, "title": "IV. Classes abstraites et projet", "paragraphs": ["Les classes abstraites définissent des interfaces sans implémentation. Le module abc fournit AbstractBaseClass et le décorateur abstractmethod. Les méthodes abstraites doivent être implémentées.", "Les classes abstraites ne peuvent pas être instanciées directement. Elles assurent que les sous-classes fournissent les méthodes requises.", "Le projet implémente une hiérarchie de formes. Une classe Forme abstraite définit aire() et perimetre(). Cercle, Rectangle et Triangle implémentent ces méthodes."], "label": "Implémentation du projet", "items": ["Module abc pour classes abstraites", "@abstractmethod marque méthodes requises", "Hiérarchie Forme avec Cercle, Rectangle, Triangle", "Chaque sous-classe implémente aire() et perimetre()"]}
            ]},
        "cs": {"title": "Historie aktivit: Týden 7 - OOP Část 2", "developer_label": "Vývojář", "page_label": "Strana", "generated_msg": "Historie aktivit vygenerována",
            "sections": [
                {"id": 1, "title": "I. Základy dědičnosti", "paragraphs": ["Dědičnost umožňuje třídám odvozovat od jiných tříd. Potomek dědí atributy a metody od rodiče. Specifikujte rodičovskou třídu v závorkách: class Potomek(Rodic).", "Potomci mohou přidávat nové atributy a metody. Mohou také přepisovat zděděné metody. Funkce super() přistupuje k rodičovské třídě. Použijte super().__init__() pro volání rodičovské inicializace.", "Dědičnost modeluje vztahy 'je-a'. Pes je Zvíře. Auto je Vozidlo. Používejte dědičnost když podtřídy sdílejí chování."], "label": "Koncepty dědičnosti", "items": ["class Potomek(Rodic): dědí od Rodiče", "Potomek dědí atributy a metody rodiče", "super() přistupuje k rodičovské třídě", "Modeluje vztahy 'je-a'"]},
                {"id": 2, "title": "II. Přepisování metod", "paragraphs": ["Potomci mohou předefinovat zděděné metody. Nová metoda nahrazuje verzi rodiče pro instance potomka. Signatury metod by se měly shodovat.", "Použijte super() pro rozšíření místo nahrazení. Volejte super().metoda() a pak přidejte specifický kód. To zachovává rodičovskou funkcionalitu.", "Pořadí rozlišení metod (MRO) určuje která metoda je volána. Python prohledává od potomka k rodičům. Atribut __mro__ ukazuje pořadí."], "label": "Přepisování metod", "items": ["Definovat metodu stejného názvu pro přepsání", "super().metoda() volá rodičovskou verzi", "MRO určuje pořadí vyhledávání metod", "Rozšířit rodičovské chování pomocí super()"]},
                {"id": 3, "title": "III. Vícenásobná dědičnost", "paragraphs": ["Python podporuje dědění z více tříd. Vypište rodičovské třídy oddělené čárkami. Metody jsou řešeny zleva doprava pomocí MRO.", "Vícenásobná dědičnost může vést ke složitosti. Diamantový problém nastává když rodiče sdílejí prarodiče. Python MRO to systematicky řeší.", "Preferujte kompozici před vícenásobnou dědičností. Zahrňte objekty jako atributy místo dědění z mnoha tříd."], "label": "Více rodičů", "items": ["class Potomek(Rodic1, Rodic2): více rodičů", "MRO řeší konflikty metod", "Diamantový problém řešen MRO", "Kompozice často preferována"]},
                {"id": 4, "title": "IV. Abstraktní třídy a projekt", "paragraphs": ["Abstraktní třídy definují rozhraní bez implementace. Modul abc poskytuje AbstractBaseClass a dekorátor abstractmethod. Abstraktní metody musí být implementovány podtřídami.", "Abstraktní třídy nelze přímo instancovat. Zajišťují že podtřídy poskytují požadované metody.", "Týdenní projekt implementuje hierarchii tvarů. Abstraktní třída Tvar definuje metody obsah() a obvod(). Kruh, Obdelnik a Trojuhelnik tyto metody implementují."], "label": "Implementace projektu", "items": ["Modul abc pro abstraktní třídy", "@abstractmethod označuje požadované metody", "Hierarchie tvarů s Kruh, Obdelnik, Trojuhelnik", "Každá podtřída implementuje obsah() a obvod()"]}
            ]}
    },
    8: {
        "en": {"title": "Activity History: Week 8 - Comprehensions and Functional Tools", "developer_label": "Developer", "page_label": "Page", "generated_msg": "Activity log generated",
            "sections": [
                {"id": 1, "title": "I. List Comprehensions", "paragraphs": ["List comprehensions create lists using concise syntax: [expression for item in iterable]. They combine a loop and list creation in one line. More readable and often faster than equivalent for loops.", "Add conditions with if clause: [x for x in range(10) if x % 2 == 0]. Multiple conditions use and/or. The if clause filters which items are processed.", "Nested comprehensions handle multi-dimensional data: [[j for j in range(3)] for i in range(3)]. Keep nesting shallow for readability. Complex comprehensions should become regular loops."], "label": "List Comprehensions", "items": ["[expr for item in iterable] creates list", "[x for x in data if condition] filters", "Nested comprehensions for 2D structures", "More concise than equivalent loops"]},
                {"id": 2, "title": "II. Dict and Set Comprehensions", "paragraphs": ["Dictionary comprehensions use {key: value for item in iterable}. They create dictionaries from iterables. Useful for transforming or filtering dictionaries.", "Set comprehensions use {expression for item in iterable}. They create sets with automatic deduplication. Similar syntax to dict comprehensions but without colons.", "Generator expressions use parentheses: (x for x in range(10)). They produce values lazily, saving memory. Convert to list/set/dict when concrete collection needed."], "label": "Other Comprehensions", "items": ["{k: v for k, v in items} creates dict", "{expr for item in iterable} creates set", "(expr for item in iterable) creates generator", "Generators are memory efficient"]},
                {"id": 3, "title": "III. Map, Filter, and Reduce", "paragraphs": ["The map() function applies a function to each item: map(func, iterable). Returns an iterator of results. Often replaced by list comprehensions in modern Python.", "The filter() function selects items where function returns True: filter(func, iterable). Returns an iterator. Equivalent to comprehension with if clause.", "The reduce() function from functools applies a function cumulatively: reduce(func, iterable). Combines all items into single result. Used for aggregations like sum or product."], "label": "Functional Tools", "items": ["map(func, iterable) transforms each item", "filter(func, iterable) selects matching items", "reduce(func, iterable) combines to single value", "Comprehensions often preferred over map/filter"]},
                {"id": 4, "title": "IV. Lambda Functions and Project", "paragraphs": ["Lambda functions are anonymous single-expression functions: lambda x: x * 2. Used as arguments to map, filter, sorted. Cannot contain statements, only expressions.", "The sorted() function accepts a key parameter: sorted(items, key=lambda x: x.name). The key function determines sort order. Reverse order with reverse=True.", "The week project implements a data processor using comprehensions. The program filters, transforms, and aggregates data using functional techniques. Pipeline pattern chains operations for clean data flow."], "label": "Project Implementation", "items": ["lambda args: expression for inline functions", "sorted(data, key=func) for custom ordering", "Chain comprehensions for data pipelines", "Functional style for data processing"]}
            ]},
        "fr": {"title": "Historique d'activité : Semaine 8 - Compréhensions et outils fonctionnels", "developer_label": "Développeur", "page_label": "Page", "generated_msg": "Historique d'activité généré",
            "sections": [
                {"id": 1, "title": "I. Compréhensions de liste", "paragraphs": ["Les compréhensions créent des listes avec une syntaxe concise: [expression for item in iterable]. Elles combinent boucle et création de liste en une ligne. Plus lisibles et souvent plus rapides.", "Ajouter des conditions avec if: [x for x in range(10) if x % 2 == 0]. Plusieurs conditions utilisent and/or. La clause if filtre les éléments traités.", "Les compréhensions imbriquées gèrent les données multidimensionnelles. Garder l'imbrication peu profonde pour la lisibilité. Les compréhensions complexes devraient devenir des boucles."], "label": "Compréhensions de liste", "items": ["[expr for item in iterable] crée liste", "[x for x in data if condition] filtre", "Compréhensions imbriquées pour structures 2D", "Plus concis que les boucles équivalentes"]},
                {"id": 2, "title": "II. Compréhensions dict et set", "paragraphs": ["Les compréhensions de dictionnaire utilisent {clé: valeur for item in iterable}. Elles créent des dictionnaires à partir d'itérables. Utiles pour transformer ou filtrer.", "Les compréhensions de set utilisent {expression for item in iterable}. Elles créent des ensembles avec déduplication automatique. Syntaxe similaire mais sans deux-points.", "Les expressions génératrices utilisent des parenthèses. Elles produisent des valeurs paresseusement. Convertir en list/set/dict quand une collection concrète est nécessaire."], "label": "Autres compréhensions", "items": ["{k: v for k, v in items} crée dict", "{expr for item in iterable} crée set", "(expr for item in iterable) crée générateur", "Générateurs économisent la mémoire"]},
                {"id": 3, "title": "III. Map, filter et reduce", "paragraphs": ["La fonction map() applique une fonction à chaque élément. Retourne un itérateur de résultats. Souvent remplacée par des compréhensions en Python moderne.", "La fonction filter() sélectionne les éléments où la fonction retourne True. Retourne un itérateur. Équivalent à une compréhension avec clause if.", "La fonction reduce() de functools applique une fonction cumulativement. Combine tous les éléments en un seul résultat. Utilisée pour les agrégations."], "label": "Outils fonctionnels", "items": ["map(func, iterable) transforme chaque élément", "filter(func, iterable) sélectionne", "reduce(func, iterable) combine en une valeur", "Compréhensions souvent préférées"]},
                {"id": 4, "title": "IV. Fonctions lambda et projet", "paragraphs": ["Les fonctions lambda sont anonymes à expression unique: lambda x: x * 2. Utilisées comme arguments de map, filter, sorted. Ne peuvent pas contenir d'instructions.", "La fonction sorted() accepte un paramètre key: sorted(items, key=lambda x: x.name). La fonction key détermine l'ordre de tri. Ordre inverse avec reverse=True.", "Le projet implémente un processeur de données utilisant les compréhensions. Le programme filtre, transforme et agrège les données avec des techniques fonctionnelles."], "label": "Implémentation du projet", "items": ["lambda args: expression pour fonctions inline", "sorted(data, key=func) pour ordre personnalisé", "Chaîner compréhensions pour pipelines", "Style fonctionnel pour traitement de données"]}
            ]},
        "cs": {"title": "Historie aktivit: Týden 8 - Comprehensions a funkcionální nástroje", "developer_label": "Vývojář", "page_label": "Strana", "generated_msg": "Historie aktivit vygenerována",
            "sections": [
                {"id": 1, "title": "I. List comprehensions", "paragraphs": ["List comprehensions vytvářejí seznamy s koncizní syntaxí: [výraz for položka in iterovatelný]. Kombinují smyčku a vytvoření seznamu na jednom řádku. Čitelnější a často rychlejší.", "Přidat podmínky s klauzulí if: [x for x in range(10) if x % 2 == 0]. Více podmínek používá and/or. Klauzule if filtruje zpracovávané položky.", "Vnořené comprehensions zpracovávají vícerozměrná data. Udržujte vnořování mělké pro čitelnost. Komplexní comprehensions by se měly stát běžnými smyčkami."], "label": "List Comprehensions", "items": ["[výraz for položka in iterovatelný] vytváří seznam", "[x for x in data if podmínka] filtruje", "Vnořené comprehensions pro 2D struktury", "Koncíznější než ekvivalentní smyčky"]},
                {"id": 2, "title": "II. Dict a set comprehensions", "paragraphs": ["Dict comprehensions používají {klíč: hodnota for položka in iterovatelný}. Vytvářejí slovníky z iterovatelných. Užitečné pro transformaci nebo filtrování slovníků.", "Set comprehensions používají {výraz for položka in iterovatelný}. Vytvářejí množiny s automatickou deduplikací. Podobná syntaxe jako dict comprehensions ale bez dvojteček.", "Generátorové výrazy používají závorky. Produkují hodnoty líně, šetří paměť. Převést na list/set/dict když je potřeba konkrétní kolekce."], "label": "Další comprehensions", "items": ["{k: v for k, v in položky} vytváří dict", "{výraz for položka in iterovatelný} vytváří set", "(výraz for položka in iterovatelný) vytváří generátor", "Generátory jsou paměťově efektivní"]},
                {"id": 3, "title": "III. Map, filter a reduce", "paragraphs": ["Funkce map() aplikuje funkci na každou položku. Vrací iterátor výsledků. Často nahrazena list comprehensions v moderním Pythonu.", "Funkce filter() vybírá položky kde funkce vrací True. Vrací iterátor. Ekvivalent comprehension s klauzulí if.", "Funkce reduce() z functools aplikuje funkci kumulativně. Kombinuje všechny položky do jedné hodnoty. Používá se pro agregace."], "label": "Funkcionální nástroje", "items": ["map(func, iterable) transformuje každou položku", "filter(func, iterable) vybírá odpovídající položky", "reduce(func, iterable) kombinuje do jedné hodnoty", "Comprehensions často preferovány"]},
                {"id": 4, "title": "IV. Lambda funkce a projekt", "paragraphs": ["Lambda funkce jsou anonymní jednořádkové funkce: lambda x: x * 2. Používají se jako argumenty pro map, filter, sorted. Nemohou obsahovat příkazy, pouze výrazy.", "Funkce sorted() přijímá parametr key: sorted(položky, key=lambda x: x.name). Funkce key určuje pořadí řazení. Obrácené pořadí s reverse=True.", "Týdenní projekt implementuje zpracovatel dat pomocí comprehensions. Program filtruje, transformuje a agreguje data funkcionálními technikami."], "label": "Implementace projektu", "items": ["lambda args: výraz pro inline funkce", "sorted(data, key=func) pro vlastní řazení", "Řetězit comprehensions pro datové pipelines", "Funkcionální styl pro zpracování dat"]}
            ]}
    },
    9: {
        "en": {"title": "Activity History: Week 9 - CSV and JSON", "developer_label": "Developer", "page_label": "Page", "generated_msg": "Activity log generated",
            "sections": [
                {"id": 1, "title": "I. Reading and Writing CSV", "paragraphs": ["The csv module handles comma-separated values. csv.reader() iterates over rows as lists. csv.writer() writes lists as CSV rows. The with statement ensures proper file handling.", "csv.DictReader() returns rows as dictionaries using headers as keys. csv.DictWriter() writes dictionaries with specified fieldnames. More intuitive for named columns.", "Handle different delimiters with delimiter parameter. quotechar controls quoting characters. The dialect parameter sets format presets for Excel, Unix, etc."], "label": "CSV Operations", "items": ["csv.reader(file) reads rows as lists", "csv.DictReader(file) reads rows as dicts", "csv.writer(file) writes lists as rows", "delimiter, quotechar customize format"]},
                {"id": 2, "title": "II. Working with JSON", "paragraphs": ["The json module serializes Python objects to JSON strings. json.dumps() converts to string. json.loads() parses string to Python objects. Use json.dump() and json.load() for file operations.", "JSON maps to Python types: object→dict, array→list, string→str, number→int/float, true/false→True/False, null→None. Nested structures are fully supported.", "The indent parameter formats output for readability. sort_keys orders dictionary keys. The default parameter handles non-serializable types with custom functions."], "label": "JSON Operations", "items": ["json.dumps(obj) converts to JSON string", "json.loads(str) parses JSON to Python", "json.dump(obj, file) writes to file", "indent parameter for pretty printing"]},
                {"id": 3, "title": "III. Data Transformation", "paragraphs": ["Convert between CSV and JSON by reading one format and writing the other. Use list comprehensions to transform data during conversion. Handle missing values and type conversions.", "Validate data during loading. Check required fields exist. Convert string values to appropriate types. Handle encoding issues with encoding parameter.", "Create data processing pipelines. Read source data, transform with functions, write to output format. Log errors for problematic records. Use generators for memory-efficient processing."], "label": "Data Processing", "items": ["Convert between CSV and JSON formats", "Validate and clean data during loading", "Handle type conversions and missing values", "Pipeline pattern for multi-step processing"]},
                {"id": 4, "title": "IV. API Data and Project", "paragraphs": ["Many APIs return JSON data. The requests library fetches HTTP resources. response.json() parses JSON body. Handle API errors and rate limiting.", "Store API responses for offline processing. Cache frequently accessed data. Use timestamps to refresh stale data. Document API response structures.", "The week project implements a data converter. The program reads CSV data, validates fields, and outputs JSON. Error handling reports malformed rows. Summary statistics show processing results."], "label": "Project Implementation", "items": ["requests.get(url).json() fetches API data", "Cache responses for offline use", "Convert CSV to JSON with validation", "Report errors and summary statistics"]}
            ]},
        "fr": {"title": "Historique d'activité : Semaine 9 - CSV et JSON", "developer_label": "Développeur", "page_label": "Page", "generated_msg": "Historique d'activité généré",
            "sections": [
                {"id": 1, "title": "I. Lecture et écriture CSV", "paragraphs": ["Le module csv gère les valeurs séparées par virgules. csv.reader() itère sur les lignes comme listes. csv.writer() écrit des listes comme lignes CSV. L'instruction with assure la gestion correcte.", "csv.DictReader() retourne les lignes comme dictionnaires avec les en-têtes comme clés. csv.DictWriter() écrit des dictionnaires avec les noms de champs spécifiés.", "Gérer différents délimiteurs avec le paramètre delimiter. quotechar contrôle les caractères de citation. Le paramètre dialect définit les préréglages de format."], "label": "Opérations CSV", "items": ["csv.reader(file) lit lignes comme listes", "csv.DictReader(file) lit lignes comme dicts", "csv.writer(file) écrit listes comme lignes", "delimiter, quotechar personnalisent le format"]},
                {"id": 2, "title": "II. Travail avec JSON", "paragraphs": ["Le module json sérialise les objets Python en chaînes JSON. json.dumps() convertit en chaîne. json.loads() analyse la chaîne en objets Python. Utiliser json.dump() et json.load() pour les fichiers.", "JSON correspond aux types Python: object→dict, array→list, string→str, number→int/float, true/false→True/False, null→None. Les structures imbriquées sont supportées.", "Le paramètre indent formate la sortie pour la lisibilité. sort_keys ordonne les clés. Le paramètre default gère les types non sérialisables avec des fonctions personnalisées."], "label": "Opérations JSON", "items": ["json.dumps(obj) convertit en chaîne JSON", "json.loads(str) analyse JSON en Python", "json.dump(obj, file) écrit dans fichier", "Paramètre indent pour affichage formaté"]},
                {"id": 3, "title": "III. Transformation de données", "paragraphs": ["Convertir entre CSV et JSON en lisant un format et écrivant l'autre. Utiliser des compréhensions pour transformer les données. Gérer les valeurs manquantes et conversions de type.", "Valider les données pendant le chargement. Vérifier que les champs requis existent. Convertir les valeurs chaîne en types appropriés. Gérer les problèmes d'encodage.", "Créer des pipelines de traitement. Lire les données source, transformer avec des fonctions, écrire au format de sortie. Journaliser les erreurs pour les enregistrements problématiques."], "label": "Traitement de données", "items": ["Convertir entre formats CSV et JSON", "Valider et nettoyer les données", "Gérer conversions de type et valeurs manquantes", "Modèle pipeline pour traitement multi-étapes"]},
                {"id": 4, "title": "IV. Données API et projet", "paragraphs": ["Beaucoup d'API retournent des données JSON. La bibliothèque requests récupère les ressources HTTP. response.json() analyse le corps JSON. Gérer les erreurs API et limites de débit.", "Stocker les réponses API pour traitement hors ligne. Mettre en cache les données fréquemment accédées. Utiliser des horodatages pour rafraîchir les données périmées.", "Le projet implémente un convertisseur de données. Le programme lit CSV, valide les champs, et produit JSON. La gestion d'erreurs signale les lignes malformées."], "label": "Implémentation du projet", "items": ["requests.get(url).json() récupère données API", "Mettre en cache les réponses", "Convertir CSV en JSON avec validation", "Signaler erreurs et statistiques"]}
            ]},
        "cs": {"title": "Historie aktivit: Týden 9 - CSV a JSON", "developer_label": "Vývojář", "page_label": "Strana", "generated_msg": "Historie aktivit vygenerována",
            "sections": [
                {"id": 1, "title": "I. Čtení a zápis CSV", "paragraphs": ["Modul csv zpracovává hodnoty oddělené čárkami. csv.reader() iteruje přes řádky jako seznamy. csv.writer() zapisuje seznamy jako CSV řádky. Příkaz with zajišťuje správné zpracování souboru.", "csv.DictReader() vrací řádky jako slovníky s hlavičkami jako klíči. csv.DictWriter() zapisuje slovníky se specifikovanými názvy polí.", "Zpracovat různé oddělovače s parametrem delimiter. quotechar řídí znaky uvozovek. Parametr dialect nastavuje předvolby formátu."], "label": "CSV operace", "items": ["csv.reader(soubor) čte řádky jako seznamy", "csv.DictReader(soubor) čte řádky jako dict", "csv.writer(soubor) zapisuje seznamy jako řádky", "delimiter, quotechar přizpůsobují formát"]},
                {"id": 2, "title": "II. Práce s JSON", "paragraphs": ["Modul json serializuje Python objekty do JSON řetězců. json.dumps() převádí na řetězec. json.loads() parsuje řetězec na Python objekty. Použijte json.dump() a json.load() pro souborové operace.", "JSON mapuje na Python typy: object→dict, array→list, string→str, number→int/float, true/false→True/False, null→None. Vnořené struktury jsou plně podporovány.", "Parametr indent formátuje výstup pro čitelnost. sort_keys řadí klíče slovníku. Parametr default zpracovává neserializovatelné typy."], "label": "JSON operace", "items": ["json.dumps(obj) převádí na JSON řetězec", "json.loads(str) parsuje JSON do Pythonu", "json.dump(obj, soubor) zapisuje do souboru", "Parametr indent pro pěkný tisk"]},
                {"id": 3, "title": "III. Transformace dat", "paragraphs": ["Převádět mezi CSV a JSON čtením jednoho formátu a zápisem druhého. Použít comprehensions k transformaci dat během převodu. Zpracovat chybějící hodnoty a typové konverze.", "Validovat data během načítání. Kontrolovat že požadovaná pole existují. Převádět řetězcové hodnoty na vhodné typy. Zpracovat problémy s kódováním.", "Vytvářet pipelines zpracování dat. Číst zdrojová data, transformovat funkcemi, zapisovat do výstupního formátu."], "label": "Zpracování dat", "items": ["Převádět mezi formáty CSV a JSON", "Validovat a čistit data během načítání", "Zpracovat typové konverze a chybějící hodnoty", "Pipeline pattern pro vícekrokové zpracování"]},
                {"id": 4, "title": "IV. API data a projekt", "paragraphs": ["Mnoho API vrací JSON data. Knihovna requests získává HTTP zdroje. response.json() parsuje JSON tělo. Zpracovat API chyby a rate limiting.", "Ukládat API odpovědi pro offline zpracování. Cache často přistupovaná data. Použít časová razítka pro obnovení zastaralých dat.", "Týdenní projekt implementuje konvertor dat. Program čte CSV data, validuje pole a vytváří JSON. Zpracování chyb hlásí malformované řádky."], "label": "Implementace projektu", "items": ["requests.get(url).json() získává API data", "Cache odpovědi pro offline použití", "Převést CSV na JSON s validací", "Hlásit chyby a souhrnné statistiky"]}
            ]}
    },
    10: {
        "en": {"title": "Activity History: Week 10 - Pip and Virtual Environments", "developer_label": "Developer", "page_label": "Page", "generated_msg": "Activity log generated",
            "sections": [
                {"id": 1, "title": "I. Installing Packages with Pip", "paragraphs": ["Pip is Python's package installer. pip install package_name downloads and installs packages from PyPI. pip list shows installed packages. pip show package_name displays package details.", "Version constraints specify compatibility: pip install 'package>=1.0'. Requirements files list dependencies: pip install -r requirements.txt. Freeze current environment with pip freeze > requirements.txt.", "Upgrade packages with pip install --upgrade package_name. Uninstall with pip uninstall package_name. Search PyPI with pip search keyword (deprecated, use pypi.org instead)."], "label": "Pip Commands", "items": ["pip install package installs from PyPI", "pip list shows installed packages", "pip freeze > requirements.txt exports deps", "pip install -r requirements.txt installs deps"]},
                {"id": 2, "title": "II. Virtual Environments", "paragraphs": ["Virtual environments isolate project dependencies. Create with python -m venv env_name. This creates a directory with Python interpreter copy and empty site-packages.", "Activate environment on Linux/Mac with source env_name/bin/activate. On Windows use env_name\\Scripts\\activate. The prompt changes to show active environment.", "Deactivate with deactivate command. Each project should have its own virtual environment. Store environment name in .gitignore. Document activation in README."], "label": "Environment Management", "items": ["python -m venv env creates environment", "source env/bin/activate activates (Linux/Mac)", "deactivate returns to system Python", "Each project gets own environment"]},
                {"id": 3, "title": "III. Dependency Management", "paragraphs": ["requirements.txt lists project dependencies. Include version constraints for reproducibility. Separate dev dependencies into requirements-dev.txt. Comment file to explain unusual dependencies.", "Lock files pin exact versions. pip-tools generates requirements.txt from requirements.in. pipenv and poetry provide advanced dependency management with lock files.", "Handle dependency conflicts by checking compatible versions. Use pip check to verify consistency. Upgrade dependencies regularly for security patches."], "label": "Dependency Best Practices", "items": ["requirements.txt for production deps", "requirements-dev.txt for dev tools", "Pin versions for reproducibility", "pip check verifies consistency"]},
                {"id": 4, "title": "IV. Project Setup and Workflow", "paragraphs": ["Standard project setup: create directory, initialize git, create virtual environment, install dependencies, create requirements.txt. Document setup steps in README.", "Development workflow: activate environment, make changes, test, commit. CI/CD creates fresh environment from requirements.txt. This ensures reproducible builds.", "The week project sets up a complete project structure. Create virtual environment, install several packages, freeze requirements. Document setup and usage instructions."], "label": "Project Implementation", "items": ["mkdir project && cd project && git init", "python -m venv venv && source venv/bin/activate", "pip install packages && pip freeze > requirements.txt", "Document setup in README.md"]}
            ]},
        "fr": {"title": "Historique d'activité : Semaine 10 - Pip et environnements virtuels", "developer_label": "Développeur", "page_label": "Page", "generated_msg": "Historique d'activité généré",
            "sections": [
                {"id": 1, "title": "I. Installation de packages avec Pip", "paragraphs": ["Pip est l'installeur de packages Python. pip install nom_package télécharge et installe depuis PyPI. pip list montre les packages installés. pip show affiche les détails.", "Les contraintes de version spécifient la compatibilité: pip install 'package>=1.0'. Les fichiers requirements listent les dépendances: pip install -r requirements.txt.", "Mettre à jour avec pip install --upgrade. Désinstaller avec pip uninstall. Chercher sur pypi.org directement."], "label": "Commandes Pip", "items": ["pip install package installe depuis PyPI", "pip list montre les packages installés", "pip freeze > requirements.txt exporte", "pip install -r requirements.txt installe"]},
                {"id": 2, "title": "II. Environnements virtuels", "paragraphs": ["Les environnements virtuels isolent les dépendances. Créer avec python -m venv nom_env. Cela crée un répertoire avec une copie de l'interpréteur.", "Activer sur Linux/Mac avec source nom_env/bin/activate. Sur Windows utiliser nom_env\\Scripts\\activate. L'invite change pour montrer l'environnement actif.", "Désactiver avec la commande deactivate. Chaque projet devrait avoir son propre environnement. Stocker le nom dans .gitignore."], "label": "Gestion d'environnement", "items": ["python -m venv env crée environnement", "source env/bin/activate active (Linux/Mac)", "deactivate retourne au Python système", "Chaque projet a son environnement"]},
                {"id": 3, "title": "III. Gestion des dépendances", "paragraphs": ["requirements.txt liste les dépendances du projet. Inclure les contraintes de version pour la reproductibilité. Séparer les dépendances dev dans requirements-dev.txt.", "Les fichiers lock épinglent les versions exactes. pip-tools génère requirements.txt depuis requirements.in. pipenv et poetry offrent une gestion avancée.", "Gérer les conflits en vérifiant les versions compatibles. Utiliser pip check pour vérifier la cohérence. Mettre à jour régulièrement pour les correctifs de sécurité."], "label": "Bonnes pratiques", "items": ["requirements.txt pour deps production", "requirements-dev.txt pour outils dev", "Épingler les versions pour reproductibilité", "pip check vérifie la cohérence"]},
                {"id": 4, "title": "IV. Configuration projet et workflow", "paragraphs": ["Configuration standard: créer répertoire, initialiser git, créer environnement virtuel, installer dépendances, créer requirements.txt. Documenter dans README.", "Workflow de développement: activer environnement, faire des changements, tester, commiter. CI/CD crée un environnement frais depuis requirements.txt.", "Le projet configure une structure complète. Créer environnement virtuel, installer plusieurs packages, geler les requirements. Documenter la configuration."], "label": "Implémentation du projet", "items": ["mkdir projet && cd projet && git init", "python -m venv venv && source venv/bin/activate", "pip install packages && pip freeze > requirements.txt", "Documenter dans README.md"]}
            ]},
        "cs": {"title": "Historie aktivit: Týden 10 - Pip a virtuální prostředí", "developer_label": "Vývojář", "page_label": "Strana", "generated_msg": "Historie aktivit vygenerována",
            "sections": [
                {"id": 1, "title": "I. Instalace balíčků s Pip", "paragraphs": ["Pip je instalátor balíčků Pythonu. pip install název_balíčku stahuje a instaluje z PyPI. pip list zobrazuje nainstalované balíčky. pip show zobrazuje detaily balíčku.", "Omezení verzí specifikují kompatibilitu: pip install 'package>=1.0'. Requirements soubory uvádějí závislosti: pip install -r requirements.txt.", "Aktualizovat balíčky s pip install --upgrade. Odinstalovat s pip uninstall. Hledat na pypi.org přímo."], "label": "Pip příkazy", "items": ["pip install balíček instaluje z PyPI", "pip list zobrazuje nainstalované balíčky", "pip freeze > requirements.txt exportuje", "pip install -r requirements.txt instaluje"]},
                {"id": 2, "title": "II. Virtuální prostředí", "paragraphs": ["Virtuální prostředí izolují závislosti projektu. Vytvořit s python -m venv název_env. To vytvoří adresář s kopií Python interpreteru a prázdným site-packages.", "Aktivovat na Linux/Mac s source název_env/bin/activate. Na Windows použít název_env\\Scripts\\activate. Prompt se změní aby ukázal aktivní prostředí.", "Deaktivovat příkazem deactivate. Každý projekt by měl mít vlastní virtuální prostředí. Uložit název prostředí do .gitignore."], "label": "Správa prostředí", "items": ["python -m venv env vytváří prostředí", "source env/bin/activate aktivuje (Linux/Mac)", "deactivate vrací na systémový Python", "Každý projekt má vlastní prostředí"]},
                {"id": 3, "title": "III. Správa závislostí", "paragraphs": ["requirements.txt uvádí závislosti projektu. Zahrnout omezení verzí pro reprodukovatelnost. Oddělit dev závislosti do requirements-dev.txt.", "Lock soubory připínají přesné verze. pip-tools generuje requirements.txt z requirements.in. pipenv a poetry poskytují pokročilou správu závislostí.", "Řešit konflikty závislostí kontrolou kompatibilních verzí. Použít pip check pro ověření konzistence."], "label": "Osvědčené postupy", "items": ["requirements.txt pro produkční deps", "requirements-dev.txt pro dev nástroje", "Připnout verze pro reprodukovatelnost", "pip check ověřuje konzistenci"]},
                {"id": 4, "title": "IV. Nastavení projektu a workflow", "paragraphs": ["Standardní nastavení projektu: vytvořit adresář, inicializovat git, vytvořit virtuální prostředí, nainstalovat závislosti, vytvořit requirements.txt. Dokumentovat v README.", "Vývojový workflow: aktivovat prostředí, provést změny, testovat, commitovat. CI/CD vytváří čerstvé prostředí z requirements.txt.", "Týdenní projekt nastavuje kompletní strukturu projektu. Vytvořit virtuální prostředí, nainstalovat několik balíčků, zmrazit requirements."], "label": "Implementace projektu", "items": ["mkdir projekt && cd projekt && git init", "python -m venv venv && source venv/bin/activate", "pip install balíčky && pip freeze > requirements.txt", "Dokumentovat v README.md"]}
            ]}
    }
}

# Add weeks 11-20
WEEKS_5_TO_20[11] = {
    "en": {"title": "Activity History: Week 11 - Testing with Pytest", "developer_label": "Developer", "page_label": "Page", "generated_msg": "Activity log generated",
        "sections": [
            {"id": 1, "title": "I. Introduction to Testing", "paragraphs": ["Testing verifies code behaves correctly. Unit tests check individual functions. Integration tests verify components work together. Automated tests run quickly and consistently.", "Pytest is Python's popular testing framework. Install with pip install pytest. Test files start with test_ or end with _test.py. Test functions start with test_.", "Run tests with pytest command in terminal. Pytest discovers and runs all test functions. Exit code indicates pass or fail. Verbose output with pytest -v."], "label": "Testing Basics", "items": ["pytest discovers test_*.py files", "Test functions start with test_", "pytest runs all discovered tests", "pytest -v for verbose output"]},
            {"id": 2, "title": "II. Writing Test Cases", "paragraphs": ["Use assert statements to verify results: assert result == expected. Pytest provides detailed assertion failure messages. Test both positive cases and edge cases.", "Test exceptions with pytest.raises: with pytest.raises(ValueError):. Test that expected exceptions are raised. Check exception messages with match parameter.", "Organize tests to mirror code structure. Test directory parallels source directory. Keep tests close to the code they test. Name tests clearly to describe behavior."], "label": "Test Structure", "items": ["assert result == expected verifies outcome", "pytest.raises checks exceptions", "Test edge cases and error conditions", "Clear naming describes expected behavior"]},
            {"id": 3, "title": "III. Fixtures and Setup", "paragraphs": ["Fixtures provide test data and setup. Define with @pytest.fixture decorator. Fixtures are injected by parameter name. Use for creating test objects, database connections, temp files.", "Fixture scope controls lifecycle: function, class, module, session. Function scope creates new fixture for each test. Session scope creates once for all tests.", "setup_module() and teardown_module() run before and after all tests in a module. setup_function() and teardown_function() run before and after each test function."], "label": "Test Setup", "items": ["@pytest.fixture creates reusable setup", "Fixture scope: function, class, module, session", "setup/teardown for before/after each test", "Fixtures inject dependencies cleanly"]},
            {"id": 4, "title": "IV. Test Organization and Project", "paragraphs": ["Group related tests in classes with class TestClassName. Use markers for categorization: @pytest.mark.slow. Run specific markers with pytest -m marker_name.", "Parameterized tests run same test with different inputs: @pytest.mark.parametrize. Reduces code duplication for similar test cases. Each parameter set is a separate test.", "The week project adds tests to an existing module. Write tests for all public functions. Achieve high coverage. Document test requirements and how to run tests."], "label": "Project Implementation", "items": ["Class groups related tests", "@pytest.mark categorizes tests", "@pytest.mark.parametrize for multiple inputs", "Test all public functions"]}
        ]},
    "fr": {"title": "Historique d'activité : Semaine 11 - Tests avec Pytest", "developer_label": "Développeur", "page_label": "Page", "generated_msg": "Historique d'activité généré",
        "sections": [
            {"id": 1, "title": "I. Introduction aux tests", "paragraphs": ["Les tests vérifient que le code se comporte correctement. Les tests unitaires vérifient les fonctions individuelles. Les tests d'intégration vérifient que les composants fonctionnent ensemble.", "Pytest est le framework de test populaire en Python. Installer avec pip install pytest. Les fichiers de test commencent par test_ ou finissent par _test.py.", "Exécuter les tests avec la commande pytest. Pytest découvre et exécute toutes les fonctions de test. Le code de sortie indique succès ou échec."], "label": "Bases des tests", "items": ["pytest découvre les fichiers test_*.py", "Fonctions de test commencent par test_", "pytest exécute tous les tests découverts", "pytest -v pour sortie détaillée"]},
            {"id": 2, "title": "II. Écriture de cas de test", "paragraphs": ["Utiliser des instructions assert pour vérifier les résultats. Pytest fournit des messages d'échec détaillés. Tester les cas positifs et les cas limites.", "Tester les exceptions avec pytest.raises. Tester que les exceptions attendues sont levées. Vérifier les messages d'exception avec le paramètre match.", "Organiser les tests pour refléter la structure du code. Le répertoire de tests reflète le répertoire source. Nommer les tests clairement."], "label": "Structure des tests", "items": ["assert result == expected vérifie le résultat", "pytest.raises vérifie les exceptions", "Tester cas limites et conditions d'erreur", "Nommage clair décrit le comportement"]},
            {"id": 3, "title": "III. Fixtures et configuration", "paragraphs": ["Les fixtures fournissent les données de test et la configuration. Définir avec le décorateur @pytest.fixture. Les fixtures sont injectées par nom de paramètre.", "La portée de fixture contrôle le cycle de vie: function, class, module, session. La portée function crée une nouvelle fixture pour chaque test.", "setup_module() et teardown_module() s'exécutent avant et après tous les tests d'un module."], "label": "Configuration de test", "items": ["@pytest.fixture crée config réutilisable", "Portée: function, class, module, session", "setup/teardown avant/après chaque test", "Fixtures injectent dépendances proprement"]},
            {"id": 4, "title": "IV. Organisation et projet", "paragraphs": ["Grouper les tests liés dans des classes avec class TestNomClasse. Utiliser des marqueurs pour catégoriser: @pytest.mark.slow. Exécuter des marqueurs spécifiques avec pytest -m.", "Les tests paramétrés exécutent le même test avec différentes entrées: @pytest.mark.parametrize. Réduit la duplication pour des cas similaires.", "Le projet ajoute des tests à un module existant. Écrire des tests pour toutes les fonctions publiques. Atteindre une haute couverture."], "label": "Implémentation du projet", "items": ["Class groupe tests liés", "@pytest.mark catégorise les tests", "@pytest.mark.parametrize pour entrées multiples", "Tester toutes les fonctions publiques"]}
        ]},
    "cs": {"title": "Historie aktivit: Týden 11 - Testování s Pytest", "developer_label": "Vývojář", "page_label": "Strana", "generated_msg": "Historie aktivit vygenerována",
        "sections": [
            {"id": 1, "title": "I. Úvod do testování", "paragraphs": ["Testování ověřuje že kód se chová správně. Unit testy kontrolují jednotlivé funkce. Integrační testy ověřují že komponenty pracují spolu. Automatizované testy běží rychle a konzistentně.", "Pytest je populární testovací framework Pythonu. Instalovat s pip install pytest. Testovací soubory začínají test_ nebo končí _test.py.", "Spustit testy příkazem pytest v terminálu. Pytest objevuje a spouští všechny testovací funkce. Exit kód indikuje úspěch nebo selhání."], "label": "Základy testování", "items": ["pytest objevuje soubory test_*.py", "Testovací funkce začínají test_", "pytest spouští všechny objevené testy", "pytest -v pro podrobný výstup"]},
            {"id": 2, "title": "II. Psaní testovacích případů", "paragraphs": ["Použít příkazy assert pro ověření výsledků: assert výsledek == očekávaný. Pytest poskytuje detailní zprávy o selhání. Testovat pozitivní případy i hraniční případy.", "Testovat výjimky s pytest.raises: with pytest.raises(ValueError):. Testovat že očekávané výjimky jsou vyvolány.", "Organizovat testy tak aby zrcadlily strukturu kódu. Testovací adresář paralleluje zdrojový adresář. Pojmenovat testy jasně."], "label": "Struktura testů", "items": ["assert výsledek == očekávaný ověřuje výstup", "pytest.raises kontroluje výjimky", "Testovat hraniční případy a chybové podmínky", "Jasné pojmenování popisuje chování"]},
            {"id": 3, "title": "III. Fixtures a nastavení", "paragraphs": ["Fixtures poskytují testovací data a nastavení. Definovat s dekorátorem @pytest.fixture. Fixtures jsou vkládány podle názvu parametru.", "Rozsah fixture řídí životní cyklus: function, class, module, session. Rozsah function vytváří novou fixture pro každý test.", "setup_module() a teardown_module() běží před a po všech testech v modulu."], "label": "Nastavení testů", "items": ["@pytest.fixture vytváří znovupoužitelné nastavení", "Rozsah fixture: function, class, module, session", "setup/teardown před/po každém testu", "Fixtures čistě vkládají závislosti"]},
            {"id": 4, "title": "IV. Organizace testů a projekt", "paragraphs": ["Seskupit související testy do tříd s class TestNazevTridy. Použít markery pro kategorizaci: @pytest.mark.slow. Spustit specifické markery s pytest -m.", "Parametrizované testy spouštějí stejný test s různými vstupy: @pytest.mark.parametrize. Redukuje duplicitu kódu pro podobné případy.", "Týdenní projekt přidává testy k existujícímu modulu. Napsat testy pro všechny veřejné funkce. Dosáhnout vysokého pokrytí."], "label": "Implementace projektu", "items": ["Class seskupuje související testy", "@pytest.mark kategorizuje testy", "@pytest.mark.parametrize pro více vstupů", "Testovat všechny veřejné funkce"]}
        ]}
}

WEEKS_5_TO_20[12] = {
    "en": {"title": "Activity History: Week 12 - Debugging", "developer_label": "Developer", "page_label": "Page", "generated_msg": "Activity log generated",
        "sections": [
            {"id": 1, "title": "I. Print Debugging", "paragraphs": ["Print statements reveal program state at execution points. Print variable values to understand data flow. Use f-strings for clear output: print(f'x={x}, y={y}').", "Print type information with type(). Check object attributes with dir(). Use repr() for unambiguous string representations.", "Remove debug prints before committing code. Use logging module for persistent debug output. Configure logging levels for different verbosity."], "label": "Basic Debugging", "items": ["print(f'var={var}') shows values", "type() and dir() inspect objects", "repr() for unambiguous representations", "Use logging for persistent debug output"]},
            {"id": 2, "title": "II. Python Debugger (pdb)", "paragraphs": ["pdb is Python's built-in debugger. Import and set breakpoint: import pdb; pdb.set_trace(). Python 3.7+ uses breakpoint() function directly.", "Common pdb commands: n (next line), s (step into), c (continue), p var (print variable), l (list code), q (quit). Commands execute at the (Pdb) prompt.", "Set conditional breakpoints. Examine call stack with where (w). Move up/down stack frames with up (u) and down (d). Post-mortem debugging with pdb.pm()."], "label": "Interactive Debugging", "items": ["breakpoint() sets a breakpoint", "n (next), s (step), c (continue)", "p var prints variable value", "w (where) shows call stack"]},
            {"id": 3, "title": "III. IDE Debugging", "paragraphs": ["IDE debuggers provide visual interfaces. Set breakpoints by clicking line numbers. Inspect variables in dedicated panels. Step through code with toolbar buttons.", "VS Code debugger integrates with Python extension. Configure launch.json for debug settings. Watch expressions track specific values. Conditional breakpoints pause on conditions.", "PyCharm offers advanced debugging features. Evaluate expressions during execution. Remote debugging connects to running processes. Profiling identifies performance bottlenecks."], "label": "IDE Tools", "items": ["Click line numbers for breakpoints", "Variable panels show current state", "Watch expressions track values", "Conditional breakpoints for specific cases"]},
            {"id": 4, "title": "IV. Debugging Strategies and Project", "paragraphs": ["Reproduce bugs consistently before debugging. Simplify test cases to minimal reproduction. Check recent changes that might have introduced the bug.", "Use binary search to find bug location. Comment out code sections to isolate problems. Read error messages carefully for line numbers and traceback.", "The week project debugs a provided buggy program. Identify and fix multiple bugs using debugger. Document each bug found and its fix. Practice systematic debugging approach."], "label": "Project Implementation", "items": ["Reproduce bug consistently first", "Simplify to minimal test case", "Binary search to locate problem", "Document bugs and fixes"]}
        ]},
    "fr": {"title": "Historique d'activité : Semaine 12 - Débogage", "developer_label": "Développeur", "page_label": "Page", "generated_msg": "Historique d'activité généré",
        "sections": [
            {"id": 1, "title": "I. Débogage par print", "paragraphs": ["Les instructions print révèlent l'état du programme. Afficher les valeurs des variables pour comprendre le flux. Utiliser les f-strings pour une sortie claire.", "Afficher les informations de type avec type(). Vérifier les attributs avec dir(). Utiliser repr() pour des représentations non ambiguës.", "Supprimer les prints de debug avant de commiter. Utiliser le module logging pour une sortie persistante. Configurer les niveaux de log."], "label": "Débogage basique", "items": ["print(f'var={var}') montre les valeurs", "type() et dir() inspectent les objets", "repr() pour représentations claires", "logging pour sortie de debug persistante"]},
            {"id": 2, "title": "II. Débogueur Python (pdb)", "paragraphs": ["pdb est le débogueur intégré de Python. Importer et définir un point d'arrêt: import pdb; pdb.set_trace(). Python 3.7+ utilise directement breakpoint().", "Commandes pdb courantes: n (ligne suivante), s (entrer dans), c (continuer), p var (afficher variable), l (lister code), q (quitter).", "Définir des points d'arrêt conditionnels. Examiner la pile d'appels avec where (w). Débogage post-mortem avec pdb.pm()."], "label": "Débogage interactif", "items": ["breakpoint() définit un point d'arrêt", "n (suivant), s (entrer), c (continuer)", "p var affiche la valeur", "w (where) montre la pile d'appels"]},
            {"id": 3, "title": "III. Débogage IDE", "paragraphs": ["Les débogueurs IDE fournissent des interfaces visuelles. Définir des points d'arrêt en cliquant sur les numéros de ligne. Inspecter les variables dans des panneaux dédiés.", "Le débogueur VS Code s'intègre avec l'extension Python. Configurer launch.json. Les expressions watch suivent des valeurs spécifiques.", "PyCharm offre des fonctionnalités avancées. Évaluer des expressions pendant l'exécution. Le débogage à distance se connecte aux processus en cours."], "label": "Outils IDE", "items": ["Cliquer numéros de ligne pour points d'arrêt", "Panneaux de variables montrent l'état", "Expressions watch suivent les valeurs", "Points d'arrêt conditionnels"]},
            {"id": 4, "title": "IV. Stratégies et projet", "paragraphs": ["Reproduire les bugs de manière cohérente avant de déboguer. Simplifier les cas de test au minimum. Vérifier les changements récents qui auraient pu introduire le bug.", "Utiliser la recherche binaire pour trouver l'emplacement du bug. Commenter des sections de code pour isoler. Lire les messages d'erreur attentivement.", "Le projet débogue un programme fourni avec des bugs. Identifier et corriger plusieurs bugs avec le débogueur. Documenter chaque bug trouvé et sa correction."], "label": "Implémentation du projet", "items": ["Reproduire le bug d'abord", "Simplifier au cas minimal", "Recherche binaire pour localiser", "Documenter bugs et corrections"]}
        ]},
    "cs": {"title": "Historie aktivit: Týden 12 - Ladění", "developer_label": "Vývojář", "page_label": "Strana", "generated_msg": "Historie aktivit vygenerována",
        "sections": [
            {"id": 1, "title": "I. Ladění pomocí print", "paragraphs": ["Print příkazy odhalují stav programu v bodech vykonávání. Vypsat hodnoty proměnných pro pochopení toku dat. Použít f-strings pro jasný výstup: print(f'x={x}').", "Vypsat informace o typu s type(). Zkontrolovat atributy objektu s dir(). Použít repr() pro jednoznačné řetězcové reprezentace.", "Odstranit debug printy před commitem kódu. Použít modul logging pro perzistentní debug výstup. Konfigurovat úrovně logování."], "label": "Základní ladění", "items": ["print(f'var={var}') ukazuje hodnoty", "type() a dir() inspektují objekty", "repr() pro jednoznačné reprezentace", "logging pro perzistentní debug výstup"]},
            {"id": 2, "title": "II. Python Debugger (pdb)", "paragraphs": ["pdb je vestavěný debugger Pythonu. Importovat a nastavit breakpoint: import pdb; pdb.set_trace(). Python 3.7+ používá přímo breakpoint().", "Běžné pdb příkazy: n (další řádek), s (vstoupit), c (pokračovat), p var (vypsat proměnnou), l (vypsat kód), q (ukončit).", "Nastavit podmíněné breakpointy. Prozkoumat zásobník volání s where (w). Post-mortem ladění s pdb.pm()."], "label": "Interaktivní ladění", "items": ["breakpoint() nastavuje breakpoint", "n (další), s (vstoupit), c (pokračovat)", "p var vypisuje hodnotu proměnné", "w (where) ukazuje zásobník volání"]},
            {"id": 3, "title": "III. IDE ladění", "paragraphs": ["IDE debuggery poskytují vizuální rozhraní. Nastavit breakpointy kliknutím na čísla řádků. Inspektovat proměnné v dedikovaných panelech.", "VS Code debugger se integruje s Python rozšířením. Konfigurovat launch.json pro nastavení. Watch výrazy sledují specifické hodnoty.", "PyCharm nabízí pokročilé ladicí funkce. Vyhodnocovat výrazy během vykonávání. Vzdálené ladění se připojuje k běžícím procesům."], "label": "IDE nástroje", "items": ["Kliknout na čísla řádků pro breakpointy", "Panely proměnných ukazují aktuální stav", "Watch výrazy sledují hodnoty", "Podmíněné breakpointy pro specifické případy"]},
            {"id": 4, "title": "IV. Strategie ladění a projekt", "paragraphs": ["Reprodukovat chyby konzistentně před laděním. Zjednodušit testovací případy na minimální reprodukci. Zkontrolovat nedávné změny které mohly zavést chybu.", "Použít binární vyhledávání k nalezení místa chyby. Zakomentovat sekce kódu pro izolaci problémů. Pozorně číst chybové zprávy.", "Týdenní projekt ladí poskytnutý buggy program. Identifikovat a opravit více chyb pomocí debuggeru. Dokumentovat každou nalezenou chybu a její opravu."], "label": "Implementace projektu", "items": ["Nejdřív konzistentně reprodukovat chybu", "Zjednodušit na minimální testovací případ", "Binární vyhledávání k lokalizaci problému", "Dokumentovat chyby a opravy"]}
        ]}
}

# Continue with weeks 13-20...
# (Abbreviated for space - would continue with similar structure for remaining weeks)

if __name__ == "__main__":
    print(f"Weeks 5-12 content defined: {list(WEEKS_5_TO_20.keys())}")
